### ISSUE TITLE
can't clear data?

### ISSUE THREAD

**Issue by xpseudonym** [Sam-Martin/export-mondo-transactions#2]
I can't clear 'client_id' and 'client_sectret' so everytime I start export-mondo-transactions-v0.0.2 it fails to ask for new  'client_id' and 'client_sectret'.

So, 'Authenticate with Mondo' button returns 'Invalid request: required parameter client_id is unknown'

Also, which do the client_id and client_secret refer to from 'User ID', 'Account ID' and 'Access token' returned from https://developers.getmondo.co.uk/apps/home process?

**Comment by Sam-Martin** [comment]
@xpseudonym the client_id and client_secret are saved to a json file in the same directory as the executable so if you delete this it should prompt again.

You want the highlighted ones from this screenshot:
![image](https://cloud.githubusercontent.com/assets/803607/15864522/643a6522-2ccf-11e6-824b-1a038d694e04.png)

**Comment by xpseudonym** [comment]
Thanks Sam, that's all sorted.  Now the next... :)
