### ISSUE TITLE
Xero says 'The bank statement is an unsupported format'

### ISSUE THREAD

**Issue by xpseudonym** [Sam-Martin/export-mondo-transactions#3]
Hi Sam 
Importing the generated OFX into xero I get the attached error

> An error occured for the following reason:
> - The bank statement is an unsupported format

![screen shot 2016-06-08 at 11 47 15-ed](https://cloud.githubusercontent.com/assets/5032475/15892619/959fc168-2d72-11e6-9a99-38379bb281e5.png)
I'm very happy to help debug - I checked the ofx as text and the transactions are there to be seen by an untrained eye

**Comment by Sam-Martin** [comment]
I suspect that the OFX file export-mondo-transactions is outputting is missing some fields that Xero is expecting.

Try comparing a working OFX file from your bank against the one export-mondo-transactions creates. Add fields one by one until it works, then let me know what I need to add!

**Comment by xpseudonym** [comment]
OK
Morgan

**Comment by Sam-Martin** [comment]
Closing as stale.
